
spring:

  datasource:
    url: jdbc:mysql://192.168.125.5:3306/test?serverTimezone=Asia/Shanghai #时区的设置
    username: root
    password: MySQL5.7
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver # com.mysql.cj.jdbc.Driver 是 mysql-connector-java 6中的
    platform: mysql
    # 下面为连接池的补充设置
    druid:
      initialSize: 10   #初始化连接个数
      minIdle: 10       #最小空闲连接个数
      maxActive: 100    #最大连接个数
      maxWait: 60000    #获取连接时最大等待时间，单位毫秒。
      timeBetweenEvictionRunsMillis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 30000     #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: select 'x' #用来检测连接是否有效的sql，要求是一个查询语句。
      testWhileIdle: true       #建议配置为true，不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: true        #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false       #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      maxPoolPreparedStatementPerConnectionSize: -1 #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      filters: stat,wall,log4j #通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat，日志用的filter:log4j，防御sql注入的filter:wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: false # 合并多个DruidDataSource的监控数据
  thymeleaf:
    cache: false #关闭模板缓存
  devtools:  # 热部署配置
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
      cluster:
        nodes:
          - 192.168.125.5:6379
          - 192.168.125.5:6380
          - 192.168.125.5:6381
          - 192.168.125.5:6382
          - 192.168.125.5:6383
          - 192.168.125.5:6384
        max-redirects: 3  # 获取失败 最大重定向次数
      lettuce:
        pool:
          max-active: 20 #连接池最大连接数（使用负值表示没有限制）
          max-idle: 8   #连接池中的最大空闲连接
          min-idle: 5   # 连接池中的最小空闲连接
           #连接超时时长（毫秒）
  rabbitmq:
      virtual-host: /
      host: 192.168.125.7
      port: 5672
      username: guest
      password: guest
###mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0